language: python
sercives:
  -docker
python:
  - "2.7"
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
